// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Аутентифицирует пользователя и возвращает токены доступа.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Вход",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токены доступа",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает ID и email авторизованного пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Мой профиль",
                "responses": {
                    "200": {
                        "description": "ID и email пользователя",
                        "schema": {
                            "$ref": "#/definitions/auth.Me"
                        }
                    },
                    "401": {
                        "description": "Не авторизован или пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Обновляет пару токенов, используя refresh токен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Обновление токенов",
                "parameters": [
                    {
                        "description": "Refresh токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новая пара токенов",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Отсутствует refresh токен",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный refresh токен",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Создает нового пользователя и возвращает его ID и email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ID и email созданного пользователя",
                        "schema": {
                            "$ref": "#/definitions/auth.Me"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или формата",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/{project_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает актуальную версию страницы для указанного проекта.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Storage"
                ],
                "summary": "Получить последний черновик",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID проекта",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON контент страницы",
                        "schema": {
                            "$ref": "#/definitions/storage.Mutation"
                        }
                    },
                    "400": {
                        "description": "Отсутствует project_id",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка получения данных",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/{project_id}/mutations": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Применяет JSON-мутацию к указанному проекту после проверки схемы и лимитов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Storage"
                ],
                "summary": "Применить мутацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID проекта",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Объект мутации",
                        "name": "mutation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.Mutation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное применение, возвращает версию",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Превышен размер payload",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Превышен лимит запросов",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/{project_id}/publications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает ID всех публикаций для указанного проекта (от новых к старым).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Список ID публикаций проекта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID проекта",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список ID публикаций",
                        "schema": {
                            "$ref": "#/definitions/publishing.PublicationIDsResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/publishing.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загружает последний черновик из storage, рендерит HTML и сохраняет bundle в объектное хранилище.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Создать публикацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID проекта",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Публикация создана",
                        "schema": {
                            "$ref": "#/definitions/publishing.Publication"
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "$ref": "#/definitions/publishing.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/publishing.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/{project_id}/publications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Получить публикацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID проекта",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID публикации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Метаданные публикации",
                        "schema": {
                            "$ref": "#/definitions/publishing.Publication"
                        }
                    },
                    "404": {
                        "description": "Публикация не найдена",
                        "schema": {
                            "$ref": "#/definitions/publishing.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/publishing.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Удалить публикацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID проекта",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID публикации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Публикация удалена"
                    },
                    "404": {
                        "description": "Публикация не найдена",
                        "schema": {
                            "$ref": "#/definitions/publishing.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/publishing.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/{project_id}/versions/{version}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает страницу указанной версии для проекта.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Storage"
                ],
                "summary": "Получить версию черновика",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID проекта",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер версии",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JSON контент страницы",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный ID или версия",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка получения данных",
                        "schema": {
                            "$ref": "#/definitions/storage.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error описание произошедшей ошибки.",
                    "type": "string",
                    "example": "описание ошибки..."
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email адрес зарегистрированного пользователя.\nRequired: true",
                    "type": "string",
                    "example": "newuser@example.com"
                },
                "password": {
                    "description": "Пароль пользователя.\nRequired: true",
                    "type": "string",
                    "example": "SuperSecretPass123"
                }
            }
        },
        "auth.Me": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email адрес электронной почты пользователя.",
                    "type": "string",
                    "example": "newuser@example.com"
                },
                "id": {
                    "description": "ID уникальный идентификатор пользователя.",
                    "type": "string",
                    "example": "507f191e810c19729de860ea"
                }
            }
        },
        "auth.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "description": "RefreshToken токен, полученный при предыдущем входе или обновлении.\nRequired: true",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email адрес для регистрации.\nRequired: true",
                    "type": "string",
                    "example": "newuser@example.com"
                },
                "password": {
                    "description": "Пароль для доступа к аккаунту.\nRequired: true",
                    "type": "string",
                    "example": "SuperSecretPass123"
                }
            }
        },
        "auth.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "AccessToken токен для авторизации защищенных запросов.",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "expires_in": {
                    "description": "ExpiresIn время жизни access токена в секундах.",
                    "type": "integer",
                    "example": 3600
                },
                "refresh_token": {
                    "description": "RefreshToken токен для получения новой пары access/refresh.",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "publishing.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "описание ошибки..."
                }
            }
        },
        "publishing.Publication": {
            "type": "object",
            "properties": {
                "assets_path": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/publishing.PublicationStatus"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "publishing.PublicationIDsResponse": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "550e8400-e29b-41d4-a716-446655440000"
                    ]
                }
            }
        },
        "publishing.PublicationStatus": {
            "type": "string",
            "enum": [
                "FINISHED"
            ],
            "x-enum-varnames": [
                "StatusFinished"
            ]
        },
        "storage.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error описание произошедшей ошибки.",
                    "type": "string",
                    "example": "описание ошибки..."
                }
            }
        },
        "storage.Mutation": {
            "type": "object"
        },
        "storage.OperationType": {
            "type": "string",
            "enum": [
                "create",
                "update",
                "delete"
            ],
            "x-enum-varnames": [
                "OperationCreate",
                "OperationUpdate",
                "OperationDelete"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "WB Landing Builder API",
	Description:      "API для управления черновиками лендингов и аутентификации пользователей.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
