FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache \
    go \
    git \
    build-base

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir \
    aiohttp \
    requests \
    pytest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["sleep", "infinity"]